  language: php

  ##  PHP versions to test  against
  php:
      - "7.0"
      - "5.6"
      - "5.5"
      - "5.4"
      - "5.3"
      - "5.2"
  sudo: false
  env:
      - WP_VERSION=latest WP_MULTISITE=0
  install:
     ## install PHPCS and Wordpress standards
    - pear install pear/PHP_CodeSniffer
    - mkdir $TRAVIS_BUILD_DIR/wordpress-coding-standards && curl -L https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/archive/master.tar.gz | tar xz --strip-components=1 -C wordpress-coding-standards
    - phpenv rehash
    - phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/wordpress-coding-standards
    - phpenv rehash
  script:
    - phpcs -p -s -v -n . --standard=./phpcs.xml --extensions=php;