name: Mirror Main Branch and Tags

on:
  push:
    branches:
      - master
    tags:
      - "*"
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Remove specific folder
        run: |
          rm -rf .github
          rm -rf CHANGELOG.md
          git rm -r --cached .github || true
          git rm -r --cached CHANGELOG.md || true

      - name: Push main branch and tags to mirror repo
        env:
          GIT_AUTHOR_NAME: "pirate-bot"
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: "pirate-bot"
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
        run: |
          git remote add mirror "https://${{ secrets.BOT_TOKEN }}@github.com/Codeinwp/themeisle-sdk"

          # Reset to a single commit with no history
          git checkout master
          git reset --soft $(git rev-list --max-parents=0 HEAD)  # Go to the first commit, keeping changes 
          git commit --amend --author="pirate-bot <${{ secrets.BOT_EMAIL }}>" -m "new changes [skip ci]"  # Create a single commit with explicit author


          # Push to the mirror repo, overwriting history
          git push mirror master --force  # Push only the master branch with new history

          # Fetch tags from the source repository
          git fetch --tags "https://${{ secrets.BOT_TOKEN }}@github.com/Codeinwp/themeisle-sdk-main"  # Source repo

          # Get a list of tags in the mirror repository
          mirror_tags=$(git ls-remote --tags mirror | awk '{print $2}' | sed 's#refs/tags/##')

          # Loop through each tag in the source repository
          for tag in $(git tag); do
            # Check if the tag exists in the mirror repository by searching mirror_tags variable
            if ! echo "$mirror_tags" | grep -w "$tag" >/dev/null 2>&1; then
              # Tag does not exist in mirror, so recreate it with a standard message
              commit_hash=$(git rev-list -n 1 "$tag")  # Get the commit hash for each tag
              git tag -f -a "$tag" "$commit_hash" -m "New release"  # Annotated tag with custom message 
              # Push this specific tag to the mirror repository
              git push mirror "refs/tags/$tag"
            else
              echo "Tag $tag already exists in mirror repository. Skipping..."
            fi
          done
      - name: Sync releases from source to target repo
        run: |
          # Fetch all releases from the source repository
          releases=$(curl -s -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
                    "https://api.github.com/repos/Codeinwp/themeisle-sdk-main/releases")

          # Loop through each release and create it in the target repository
          for row in $(echo "${releases}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }

            tag_name=$(_jq '.tag_name')
            release_name=$(_jq '.name')
            draft=$(_jq '.draft')
            prerelease=$(_jq '.prerelease')

            # Create the release in the target repository
            curl -s -X POST -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/Codeinwp/themeisle-sdk/releases \
              -d "{
                \"tag_name\": \"${tag_name}\",
                \"name\": \"${release_name}\",
                \"body\": \"\",
                \"draft\": ${draft},
                \"prerelease\": ${prerelease}
              }"
          done
