name: Mirror Main Branch and Tags

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push main branch and tags to mirror repo
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
          TARGET_REPO: 'https://github.com/Codeinwp/themeisle-sdk-lib.git'
        run: |
          git remote add mirror "$TARGET_REPO"
          git push mirror master --force  # Push only the main branch
          git push mirror --tags --force  # Push all tags
