name: Mirror Main Branch and Tags

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Remove specific folder
        run: |
          rm -rf .github
          git rm -r --cached .github || true

      - name: Push main branch and tags to mirror repo
        env:
          GIT_AUTHOR_NAME: "pirate-bot"
          GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
          GIT_COMMITTER_NAME: "pirate-bot"
          GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
        run: |
          git remote add mirror "https://${{ secrets.BOT_TOKEN }}@github.com/Codeinwp/themeisle-sdk-lib"
          
          # Reset to a single commit with no history
          git checkout master
          git reset --soft $(git rev-list --max-parents=0 HEAD)  # Go to the first commit, keeping changes 
          git commit --amend --author="pirate-bot <${{ secrets.BOT_EMAIL }}}" -m "sync [skip ci]"  # Create a single commit with explicit author
          
          # Push to the mirror repo, overwriting history
          git push mirror master --force  # Push only the master branch with new history
          git push mirror --tags --force
