name: Smoke Tests

on:
  schedule:
    - cron: "0 0 * * 1" # every Monday at midnight

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e:
    name: Smoke Tests
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: simplexml
      - name: Check out source files
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Install composer deps
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: Install npm deps
        run: |
          npm ci
          npm install -g playwright-cli
          npx playwright install --with-deps chromium
      - name: Install environment
        run: |
          npm run env:start
      - name: Run the tests
        run: |
          npm run test:e2e:playwright:formbricks
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-playwright-results
          path: artifacts
          retention-days: 1
          if-no-files-found: ignore
